micronaut:
  application:
    name: chatterbox
datasources:
  default:
    url: jdbc:mysql://localhost:3306/chatterbox?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: ''
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: none
liquibase:
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.xml'
