/*
 * chatterbox - a (not so helpful) Discord bot custom written for a private server
 * Copyright (C) 2021 Ryan Morrison
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package net.ryanmorrison.chatterbox.persistence.repository;

import io.micronaut.data.annotation.Repository;
import io.micronaut.data.repository.CrudRepository;
import net.ryanmorrison.chatterbox.persistence.model.ShoutHistory;

/**
 * Repository interface for {@link ShoutHistory}s. Concrete implementation auto-generated by Micronaut Data at runtime.
 *
 * @author Ryan Morrison
 * @since 1.0
 */
@Repository
public interface ShoutHistoryRepository extends CrudRepository<ShoutHistory, Long> {

    int countByChannelIdAndMessageId(long channelId, long messageId);

    ShoutHistory findFirstByChannelId(long channelId);

    void deleteByChannelId(long channelId);
}
